CREATE TABLE styles (
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	post uuid NOT NULL UNIQUE REFERENCES coleccion_posts(id),
	top_style text NULL,
	left_style text NULL,
	width_style text NULL,
	height_style text NULL,
	z_index INTEGER NULL
);
